baseURL = "https://sl.shoogle.net/sierra-leone/"
languageCode = "en"
title = "Sierra Leone"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "sierra-leone"

[taxonomies]
  shop = "shops"

